interface CategoryPageForHeadless {
  categories: CategoryForHeadless[];
}

interface ProductPageForHeadless {
  product: ProductForHeadless;
}

interface CategoryForHeadless {
  parentId: string | null;
  autoIncrement: number;
  mediaId: string | null;
  name: string | null;
  breadcrumb: string[];
  level: number;
  active: boolean;
  childCount: number;
  displayNestedProducts: boolean;
  parent: Category | null;
  children: Category[] | null;
  translations: CategoryTranslation[] | null;
  media: Media | null;
  products: Product[] | null;
  nestedProducts: Product[] | null;
  afterCategoryId: string | null;
  customFields: CustomField[];
  tags: Tag[] | null;
  cmsPageId: string | null;
  cmsPage: CmsPage | null;
  slotConfig: [] | null;
  externalLink: string | null;
  visible: boolean;
  type: string;
  description: string;
  id: string;
  parentVersionId: string;
  afterCategoryVersionId: string;
}

interface ProductForCategoryHeadless {
  calculatedListingPrice: ListingPrice[];
  calculatedPrices: Price[];
  calculatedPrice: CalculatedPrice;
  sortedProperties: PropertyGroup[] | null;
  isNew: boolean;
  parentId: string | null;
  childCount: number;
  autoIncrement: number;
  taxId: string | null;
  manufacturerId: string | null;
  unitId: string | null;
  active: boolean;
  displayGroup: string;
  price: Price[] | null;
  manufacturerNumber: string | null;
  ean: string | null;
  productNumber: string;
  stock: number;
  availableStock: number | null;
  available: boolean;
  deliveryTimeId: string | null;
  deliveryTime: DeliveryTime;
  restockTime: number;
  isCloseout: boolean | null;
  purchaseSteps: number | null;
  maxPurchase: number | null;
  minPurchase: number | null;
  purchaseUnit: number | null;
  referenceUnit: number | null;
  shippingFree: boolean | null;
  purchasePrice: number | null;
  markAsTopseller: boolean | null;
  weight: number | null;
  width: number | null;
  height: number | null;
  length: number | null;
  releaseDate: Date;
  categoryTree: [] | null;
  optionsIds: [] | null;
  propertyIds: [] | null;
  additionalText: string | null;
  name: string | null;
  keywords: string | null;
  description: string | null;
  metaTitle: string | null;
  packUnit: string | null;
  tax: Tax;
  manufacturer: ProductManufacturer | null;
  unit: Unit | null;
  prices: ProductPrice[];
  listingPrices: ListingPrice[] | null;
  cover: ProductMedia;
  parent: Product;
  children: Product[];
  media: ProductMedia[];
  translations: ProductTranslation[];
  categories: Category[];
  tags: Tag[];
  properties: PropertyGroupOption[] | null;
  options: PropertyGroupOption[] | null;
  categoriesRo: Category[] | null;
  coverId: string | null;
  customFields: CustomField[];
  tagIds: [] | null;
  productReviews: ProductReview[] | null;
  ratingAverage: number | null;
  extensions: [];
  id: string;
  parentVersionId: string;
  productManufacturerVersionId: string;
  productMediaVersiond: null;
}

interface ProductForHeadless {
  calculatedListingPrice: ListingPrice[];
  calculatedPrices: Price[];
  calculatedPrice: CalculatedPrice;
  sortedProperties: PropertyGroup[] | null;
  isNew: boolean;
  parentId: string | null;
  childCount: number;
  autoIncrement: number;
  taxId: string | null;
  manufacturerId: string | null;
  unitId: string | null;
  active: boolean;
  displayGroup: string;
  price: Price[] | null;
  manufacturerNumber: string | null;
  ean: string | null;
  productNumber: string;
  stock: number;
  availableStock: number | null;
  available: boolean;
  deliveryTimeId: string | null;
  deliveryTime: DeliveryTime;
  restockTime: number;
  isCloseout: boolean | null;
  purchaseSteps: number | null;
  maxPurchase: number | null;
  minPurchase: number | null;
  purchaseUnit: number | null;
  referenceUnit: number | null;
  shippingFree: boolean | null;
  purchasePrice: number | null;
  markAsTopseller: boolean | null;
  weight: number | null;
  width: number | null;
  height: number | null;
  length: number | null;
  releaseDate: Date;
  categoryTree: [] | null;
  optionsIds: [] | null;
  propertyIds: [] | null;
  additionalText: string | null;
  name: string | null;
  keywords: string | null;
  description: string | null;
  metaTitle: string | null;
  packUnit: string | null;
  tax: Tax;
  manufacturer: ProductManufacturer | null;
  unit: Unit | null;
  prices: ProductPrice[];
  listingPrices: ListingPrice[] | null;
  cover: ProductMedia;
  parent: Product;
  children: Product[];
  media: ProductMedia[];
  translations: ProductTranslation[];
  categories: Category[];
  tags: Tag[];
  properties: PropertyGroupOption[] | null;
  options: PropertyGroupOption[] | null;
  categoriesRo: Category[] | null;
  coverId: string | null;
  customFields: CustomField[];
  tagIds: [] | null;
  productReviews: ProductReview[] | null;
  ratingAverage: number | null;
  extensions: [];
  id: string;
  parentVersionId: string;
  productManufacturerVersionId: string;
  productMediaVersiond: null;
}
