import { ShippingMethodCollection } from "../shipping/ShippingMethodCollection";
import { OrderCollection } from "../checkout/OrderCollection";
import { CategoryEntity } from '../category/CategoryEntity';
import { NewsletterRecipientCollection } from "../newsletter/NewsletterRecipientCollection";
import { LanguageEntity } from "../context/language/LanguageEntity";
import { LanguageCollection } from "../context/language/LanguageCollection";
import { SalesChannelTypeEntity } from "./SalesChannelTypeEntity";
import { ProductReviewColletion } from "../product/ProductReviewColletion";
import { ProductVisibilityCollection } from "../product/ProductVisibilityCollection";
import { SalesChannelDomainCollection } from "../state-machine/SalesChannelDomainCollection";
import { CurrencyTranslationCollection } from "../context/currency/CurrencyTranslationCollection";
import { PromotionSalesChannelCollection } from "../discount/PromotionSalesChannelCollection";
import { ShippingMethodPriceEntity } from "../price/ShippingMethodPriceEntity";
import { SystemConfigCollection } from "../system/SystemConfigCollection";
import { SalesChannelTranslationCollection } from "./SalesChannelTranslationCollection";
import { CountryCollection } from "../customer/CountryCollection";
import { CountryEntity } from "../customer/CountryEntity";
import { PaymentMethodEntity } from "../checkout/PaymentMethodEntity";
import CustomerCollection from "../customer/CustomerCollection";
import { MailHeaderFooterEntity } from "../mail/MailHeaderFooterEntity";
import { CustomerGroup } from "../customer/CustomerGroup";
import { MailTemplateSalesChannelCollection } from "../mail/MailTemplateSalesChannelCollection";
import { NumberRangeSalesChannelCollection } from "../number-range/NumberRangeSalesChannelCollection";
import { DocumentBaseConfigDefinition } from "../system/DocumentBaseConfigDefinition";
import { PaymentMethodCollection } from "../checkout/PaymentMethodCollection";
import { CurrencyEntity } from "../context/currency/CurrencyEntity";
export interface SalesChannelEntity {
    typeId: string;
    languageId: string;
    currencyId: string;
    paymentMethodId: string;
    shippingMethodId: string;
    countryId: string;
    navigationCategoryId: string;
    footerCategoryId: string | null;
    serviceCategoryId: string | null;
    name: string | null;
    shortName: string | null;
    accessKey: string;
    currencies: CurrencyTranslationCollection | null;
    languages: LanguageCollection | null;
    configuration: [] | null;
    active: boolean;
    type: SalesChannelTypeEntity | null;
    currency: CurrencyEntity | null;
    language: LanguageEntity | null;
    paymentMethod: PaymentMethodEntity | null;
    shippingMethod: ShippingMethodPriceEntity | null;
    country: CountryEntity | null;
    orders: OrderCollection | null;
    customers: CustomerCollection | null;
    countries: CountryCollection | null;
    paymentMethods: PaymentMethodCollection | null;
    shippingMethods: ShippingMethodCollection | null;
    translations: SalesChannelTranslationCollection | null;
    domains: SalesChannelDomainCollection | null;
    systemConfigs: SystemConfigCollection | null;
    customFields: [] | null;
    naigationCategory: CategoryEntity | null;
    footerCategory: CategoryEntity | null;
    serviceCategory: CategoryEntity | null;
    productVisibilities: ProductVisibilityCollection | null;
    mailTemplates: MailTemplateSalesChannelCollection | null;
    mailHeaderFooterId: string | null;
    numberRangeSalesChannels: NumberRangeSalesChannelCollection | null;
    mailHeaderFooter: MailHeaderFooterEntity | null;
    customerGroupId: string | null;
    customerGroup: CustomerGroup | null;
    newsletterRecipients: NewsletterRecipientCollection | null;
    promotionSalesChannels: PromotionSalesChannelCollection | null;
    documentBaseConfigSalesChannels: DocumentBaseConfigDefinition | null;
    productReviews: ProductReviewColletion | null;
}

