import { TagCollection } from "../../system/tag/Tag"
import { ProductMedia } from "./ProductMedia";
import { TaxEntity } from "../../system/tax/TaxEntity";
import { UnitEntity } from "../../system/unit/UnitEntity";
import { ProductReviewCollection } from "./ProductReviewCollection";
import { ListingPriceCollection } from "../../framework/pricing/ListingPriceCollection";
import { PriceCollection } from "../../framework/pricing/PriceCollection";
import { CalculatedPrice } from "../../checkout/cart/price/CalculatedPrice";
import { ProductPriceCollection } from "./ProductPriceCollection";
import { PropertyGroupCollection } from "../property/PropertyGroupCollection";
import { ProductCollection } from "./ProductCollection";
import { ProductMediaCollection } from "./ProductMediaCollection";
import { DeliveryTime } from "../../checkout/delivery/DeliveryTime";
import { ProductManufacturer } from "./ProductManufacturer";
import { ProductTranslationCollection } from "./ProductTranslationCollection";
import { PropertyGroupOptionCollection } from "../property/PropertyGroupOptionCollection";
import { CategoryCollection } from "../category/CategoryCollection";

export interface Product {
    calculatedListingPrice: ListingPriceCollection;
    calculatedPrices: PriceCollection;
    calculatedPrice: CalculatedPrice;
    sortedProperties: PropertyGroupCollection | null;
    isNew: boolean;
    parentId: string|null;
    childCount: number;
    autoIncrement: number;
    taxId: string|null;
    manufacturerId: string|null;
    unitId: string|null;
    active: boolean;
    displayGroup: string;
    price: PriceCollection|null;
    manufacturerNumber: string|null;
    ean: string|null;
    productNumber: string;
    stock: number;
    availableStock: number|null;
    available: boolean;
    deliveryTimeId: string|null; 
    deliveryTime: DeliveryTime;
    restockTime: number;
    isCloseout: boolean|null;
    purchaseSteps: number|null;
    maxPurchase: number|null;
    minPurchase: number|null;
    purchaseUnit: number|null;
    referenceUnit: number|null;
    shippingFree: boolean|null;
    purchasePrice: number|null;
    markAsTopseller: boolean|null;
    weight: number|null;
    width: number|null; 
    height: number|null; 
    length: number|null; 
    releaseDate: Date; 
    categoryTree: []|null; 
    optionsIds: []|null;
    propertyIds: []|null;
    additionalText: string|null;
    name: string|null;
    keywords: string|null;
    description: string|null;
    metaTitle: string|null;
    packUnit: string|null;
    tax: TaxEntity;
    manufacturer: ProductManufacturer|null;
    unit: UnitEntity|null;
    prices: ProductPriceCollection;
    listingPrices: ListingPriceCollection | null; 
    cover: ProductMedia;
    parent: Product;
    children: ProductCollection;
    media: ProductMediaCollection;
    translations: ProductTranslationCollection;
    categories: CategoryCollection;
    tags: TagCollection;
    properties: PropertyGroupOptionCollection|null;
    options: PropertyGroupOptionCollection|null;
    categoriesRo: CategoryCollection|null;
    coverId: string|null;
    customFields: []|null;
    tagIds: []|null; 
    productReviews: ProductReviewCollection|null; 
    ratingAverage: number|null;
    extensions: [];
    id: string;
    parentVersionId: string;
    productManufacturerVersionId: string;
    productMediaVersiond: null  
}