import { ShippingMethodCollection } from "../../checkout/shipping/ShippingMethodCollection";
import { OrderCollection } from "../../checkout/order/OrderCollection";
import { Category } from '../../content/category/Category';
import { NewsletterRecipientCollection } from "../../content/newsletter/NewsletterRecipientCollection";
import { Language } from "../../framework/language/Language";
import { LanguageCollection } from "../../framework/language/LanguageCollection";
import { SalesChannelTypeEntity } from "./SalesChannelTypeEntity";
import { ProductReviewColletion } from "../../content/product/ProductReviewColletion";
import { ProductVisibilityCollection } from "../../content/product/ProductVisibilityCollection";
import { SalesChannelDomainCollection } from "./SalesChannelDomainCollection";
import { CurrencyTranslationCollection } from "../currency/CurrencyTranslationCollection";
import { PromotionSalesChannelCollection } from "../../checkout/promotion/PromotionSalesChannelCollection";
import { ShippingMethodPrice } from "../../checkout/shipping/ShippingMethodPrice";
import { SystemConfigCollection } from "../system-config/SystemConfigCollection";
import { SalesChannelTranslationCollection } from "./SalesChannelTranslationCollection";
import { CountryCollection } from "../country/CountryCollection";
import { Country } from "../country/Country";
import { PaymentMethod } from "../../checkout/payment/PaymentMethod";
import CustomerCollection from "../../checkout/customer/CustomerCollection";
import { MailHeaderFooter } from "../../content/mail-template/MailHeaderFooter";
import { CustomerGroup } from "../../checkout/customer/CustomerGroup";
import { MailTemplateSalesChannelCollection } from "../../content/mail-template/MailTemplateSalesChannelCollection";
import { NumberRangeSalesChannelCollection } from "../number-range/NumberRangeSalesChannelCollection";
import { DocumentBaseConfigDefinition } from "../../checkout/document/DocumentBaseConfigDefinition";
import { PaymentMethodCollection } from "../../checkout/payment/PaymentMethodCollection";
import { Currency } from "../currency/Currency";
export interface SalesChannelEntity {
    typeId: string;
    languageId: string;
    currencyId: string;
    paymentMethodId: string;
    shippingMethodId: string;
    countryId: string;
    navigationCategoryId: string;
    footerCategoryId: string | null;
    serviceCategoryId: string | null;
    name: string | null;
    shortName: string | null;
    accessKey: string;
    currencies: CurrencyTranslationCollection | null;
    languages: LanguageCollection | null;
    configuration: [] | null;
    active: boolean;
    type: SalesChannelTypeEntity | null;
    currency: Currency | null;
    language: Language | null;
    paymentMethod: PaymentMethod | null;
    shippingMethod: ShippingMethodPrice | null;
    country: Country | null;
    orders: OrderCollection | null;
    customers: CustomerCollection | null;
    countries: CountryCollection | null;
    paymentMethods: PaymentMethodCollection | null;
    shippingMethods: ShippingMethodCollection | null;
    translations: SalesChannelTranslationCollection | null;
    domains: SalesChannelDomainCollection | null;
    systemConfigs: SystemConfigCollection | null;
    customFields: [] | null;
    naigationCategory: Category | null;
    footerCategory: Category | null;
    serviceCategory: Category | null;
    productVisibilities: ProductVisibilityCollection | null;
    mailTemplates: MailTemplateSalesChannelCollection | null;
    mailHeaderFooterId: string | null;
    numberRangeSalesChannels: NumberRangeSalesChannelCollection | null;
    mailHeaderFooter: MailHeaderFooter | null;
    customerGroupId: string | null;
    customerGroup: CustomerGroup | null;
    newsletterRecipients: NewsletterRecipientCollection | null;
    promotionSalesChannels: PromotionSalesChannelCollection | null;
    documentBaseConfigSalesChannels: DocumentBaseConfigDefinition | null;
    productReviews: ProductReviewColletion | null;
}

