export const PAGE_CHECKOUT = "/checkout"
export const PAGE_ACCOUNT = "/poland/test/account/profile"
export const PAGE_LOGIN = "/login"
export const PAGE_SEARCH = "/search"
export const PAGE_ORDER_SUCCESS = "/order"
export const PAGE_WISHLIST = "/wishlist"
